### ISSUE TITLE
Incompatible with Ruby 2.1.2

### ISSUE THREAD

**Issue by elsom25** [nixme/jazz_hands#25]
Just switched a project over too ruby 2.1.2, and it seems `jazz_hands`'s dependencies kill the bundle.

```
Using debugger-ruby_core_source 1.3.4

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/me/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
  --with-opt-dir
  --with-opt-include
  --without-opt-include=${opt-dir}/include
  --with-opt-lib
  --without-opt-lib=${opt-dir}/lib
  --with-make-prog
  --without-make-prog
  --srcdir=.
  --curdir
  --ruby=/Users/me/.rvm/rubies/ruby-2.1.2/bin/ruby
/Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1573:in `stat': No such file or directory @ rb_file_s_stat - ./212/ruby_debug.h (Errno::ENOENT)
  from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
  from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1587:in `fu_each_src_dest0'
  from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
  from /Users/me/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
  from extconf.rb:83:in `block in <main>'
  from extconf.rb:82:in `each'
  from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/me/.rvm/gems/ruby-2.1.2@redsteel-site/gems/debugger-1.6.6 for inspection.
Results logged to /Users/me/.rvm/gems/ruby-2.1.2@redsteel-site/extensions/x86_64-darwin-13/2.1.0/debugger-1.6.6/gem_make.out
An error occurred while installing debugger (1.6.6), and Bundler cannot continue.
Make sure that `gem install debugger -v '1.6.6'` succeeds before bundling.
```

**Comment by nixme** [comment]
Probably cause debugger needs to be updated. 

Switch your Gemfile to:

``` ruby
gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
gem 'pry-byebug'   # This may or may not work with 2.1.2 either, so remove if you still get errorrs
```

Then `bundle update jazz_hands pry-byebug`

I need to release a new version of jazz_hands with this whole debugger mess fixed. Sorry for the delay everyone. I'll try to get to it this weekend.

**Comment by elsom25** [comment]
Well this did fix it—thanks for the prompt reply!

**Comment by juni0r** [comment]
Fixed that issue for me, too. Thanks! I couldn't update my bundle because it coughed up when trying to build native extensions for debugger. Tried a couple of suggested fixes and this one finally did the trick.

**Comment by neohunter** [comment]
This is closed almost one year ago but still have this problem due to debugger gem that is not compatible with ruby 2.x

**Comment by brobertsaz** [comment]
I guess jazz_hands never was updated.  I just had the same issue but the 'bring-your-own-debugger' did the trick.

**Comment by plribeiro3000** [comment]
@brobertsaz Try my fork [`jazz_fingers`](https://github.com/plribeiro3000/jazz_fingers). It is pretty much the same but with all the latest version of the dependencies.

**Comment by brobertsaz** [comment]
@plribeiro3000 thanks and i will try it out in just a minute :)

**Comment by thom801** [comment]
I was getting these two errors:
1. Running `bundle install` after adding `jazz_hands` to my Gemfile failed and said it could not find a compatible version of `pry`.
2. Running `bundle update` gave me a build error while installing `debugger 1.6.8` because as people have said here, it's not compatible with ruby v2.1+.

Here's how I fixed it:

I replaced 

``` ruby
gem 'jazz_hands'
```

in my Gemfile with:

``` ruby
gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
gem 'pry-byebug'
```

Then `bundle update`. That fixed it! Thanks @nixme for the fix.

Note: Running `bundle install` still gave me the pry build error. Make sure you update.
